name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  build_snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Snapcraft
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --verbose --all --tests

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

  publish_snap:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build, build_snap, clippy, format]
    steps:
      - name: Download Snap Artifact
        uses: actions/download-artifact@v2
        with:
          name: snap

      - name: Get snap filename
        id: get_filename
        run: 'echo ::set-output name=filename::$(ls *.snap)'

      - name: Publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.get_filename.outputs.filename }}
          release: edge
